### ISSUE TITLE
dmg percentage calculation 

### ISSUE THREAD

**Issue by Saline3** [maxrios/PvpCustomDamage#1]
setting it to 33% instantly kills a player, where it should only do 33% more damage from its base. (armor is full protection iv & sword is sharpness v)

https://user-images.githubusercontent.com/119183365/204142512-878616fb-4fd4-4139-be9e-18ed97609b84.mp4

**Comment by maxrios** [comment]
19e04d1 fixes the issue. Forgot to convert the multiply value to a percentage :d

**Comment by maxrios** [comment]
Latest release it up
